### ISSUE TITLE
SendHidEvent Errors  panic: libusb: pipe error [code -9]

### ISSUE THREAD

**Issue by byf6663** [Tryanks/go-accessoryhid#2]
panic: libusb: pipe error [code -9]

**Comment by Tryanks** [comment]
Thanks for the feedback, but need more info.
Can you provide the minimal implementation of the relevant code you are using, the Android device and the USB connection status?

**Comment by Tryanks** [comment]
https://github.com/Tryanks/go-accessoryhid/issues/6#issuecomment-2702895086
It's my bad :(
